### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#69]
For Linux users, we should have a `man` page with all the info from the readme, wiki and `--help` flag in a readable and coherent form; (note: all info from the man page should also be available on the wiki, e.g. through a text dump of the man page)

It should come with an installation script (Makefile or so) that installs `kotnetcli` under `/usr/local/bin` and the man page under `/usr/local/share/man/man1`

The [Makefile](https://github.com/jovanbulck/jo-shell/blob/master/Makefile) and/or dialog-based [installer shell script](https://github.com/jovanbulck/jo-shell/blob/master/installer.sh) of the `jsh` shell could be a good place to start

Marking this for release 3.0.0 'Cape Cod' ?

**Comment by jovanbulck** [comment]
the installer could also help the user to resolve dependencies

**Comment by GijsTimmers** [comment]
I completely agree on the necessity of a `man` page. Some of my thoughts on the installer:

- I think that the Linux repository system is one of its biggest advantages compared to other operating systems. Although it may be hard to get `kotnetcli` into, say, the Ubuntu repositories, we could at least 'hook into it' by using .deb and .rpm files, which are very to install in modern distributions. For Arch, it will probably be easier: we can just create an AUR entry. In my opinion, this is cleaner than writing a separate installer.

- Of course, a [NSIS](http://nsis.sourceforge.net/Main_Page) installer would be a very interesting choice for Windows users.

- Another very interesting thing would be to upload kotnetcli as a [PyPI](https://pypi.python.org/pypi) package, so that users could install kotnetcli via `pip`. Considering that all `kotnetcli` dependancies are installable through `pip`, it would be very cool to see `pip` pull in all the necessary dependancies and then put the `kotnetcli` files into the $PATH.

**Comment by jovanbulck** [comment]
> Another very interesting thing would be to upload kotnetcli as a PyPI package,

I like this idea :-)

**Comment by GijsTimmers** [comment]
I've been looking around for some pointers on how to create a `$PATH` executable for PyPI packages.

Seems like the most common way to do it is [using the `entry_points` statement along with `console_scripts`](http://www.scotttorborg.com/python-packaging/command-line-scripts.html).

What this basically does, is linking an executable in `$PATH` to a specific _function_ in your package.

Please note that `kotnetcli` reads command-line-arguments when executed. Linking an executable to a _function_ will therefore result in not being able to parse command-line arguments. An example of this problem can be found [here](http://stackoverflow.com/questions/2853088/setuptools-not-passing-arguments-for-entry-points).

I'm not sure what the right approach to this will be. 

Some other programs that use `entry_points`:

- [grip](https://github.com/joeyespo/grip/blob/master/setup.py#L48)
- [mps-youtube](https://github.com/np1/mps-youtube/blob/develop/setup.py#L28)
- [keyring](https://bitbucket.org/kang/python-keyring-lib/src/b2e88501a6a9bc7f1c7c230a6431ac0860ff4e50/setup.py?at=default#cl-93)

**Comment by GijsTimmers** [comment]
The PyPI stuff is as good as done. Can you do the man page stuff?

**Comment by jovanbulck** [comment]
> The PyPI stuff is as good as done. Can you do the man page stuff?

Writing the man page itself is not a lot of work, but we'll have to keep it up-to-date. Moreover, the `--help` output is rather self-contained and readable. My original proposal for a man page is therefore not needed anymore. In my opinion you can close this issue for now..

**Comment by GijsTimmers** [comment]
Alright, closing
