### ISSUE TITLE
BeautifulSoup warning

### ISSUE THREAD

**Issue by Forceflow** [GijsTimmers/kotnetcli#99]
Ubuntu 15.10, dependencies installed. Seems to work well, but get a warning when executing script:

```
Gegevens invoeren..... [ OK ]
Gegevens opsturen..... [ OK ]
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Download:  [==========][100%]
```

**Comment by GijsTimmers** [comment]
Hi, thank you for using `kotnetcli`, and thank you for reporting this bug. This problem is fixed in the `dev` branch. You can either switch to the dev branch:

```
git pull
git checkout dev
./kotnetcli-runner.py
```

or patch `worker.py` on the `master` branch:

    gedit worker.py

Navigate to line 90. Change

            soup = BeautifulSoup(html)

to

            soup = BeautifulSoup(html, "html.parser")

At the moment, I'm not _at kot_. Could you please let me know whether this fixed your problem?

Thank you very much.

**Comment by Forceflow** [comment]
Dev branch looks to have more problems, kotnetcli-runner.py doesn't even start (tab for more arguments error). 

Figured out the worker.py call myself too, I'll make a pull request :)

**Comment by GijsTimmers** [comment]
Thank you.

**Comment by Forceflow** [comment]
Thank you for the good script :)
